name: ML CI
on: [pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      
    steps:
      - uses: actions/checkout@v3

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: ML-Client - Turn on 'editable' mode
        working-directory: ./machine-learning-client 
        run: |
          pipenv install 

      - name: ML-Client - Test with pytest
        working-directory: ./machine-learning-client 
        run: |
          pipenv run python -m pytest